// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzJ1EL4cvuD0WXrxI9Xjaguk88mdhUNd8',
    appId: '1:450473717862:web:8c133b786db108616abda7',
    messagingSenderId: '450473717862',
    projectId: 'instagram-clone-cc9e6',
    authDomain: 'instagram-clone-cc9e6.firebaseapp.com',
    storageBucket: 'instagram-clone-cc9e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRDnd-XpYJ86gn8bf9Rrn13msUGDmIaL4',
    appId: '1:450473717862:android:973560cafe6cda7d6abda7',
    messagingSenderId: '450473717862',
    projectId: 'instagram-clone-cc9e6',
    storageBucket: 'instagram-clone-cc9e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6tnxNF7FV9fTeW2ulikkrJ8b42UOEZc',
    appId: '1:450473717862:ios:0b476cef8bb439f76abda7',
    messagingSenderId: '450473717862',
    projectId: 'instagram-clone-cc9e6',
    storageBucket: 'instagram-clone-cc9e6.appspot.com',
    iosBundleId: 'com.example.instagramClonee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzJ1EL4cvuD0WXrxI9Xjaguk88mdhUNd8',
    appId: '1:450473717862:web:999411f86f0fa5bd6abda7',
    messagingSenderId: '450473717862',
    projectId: 'instagram-clone-cc9e6',
    authDomain: 'instagram-clone-cc9e6.firebaseapp.com',
    storageBucket: 'instagram-clone-cc9e6.appspot.com',
  );
}
